#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    lib = bld.create_obj('cc', 'staticlib')
    lib.find_sources_in_dirs('.')
    lib.includes = '../extra/b25/src'
    lib.name = 'capsts_staticlib'
    lib.target = 'capsts'
    lib.uselib_local = 'aribstdb25_staticlib'
    lib.uselib = 'GLIB LIBPCSCLITE LIBUSB'
