#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    bin = bld.create_obj('cc', 'program')
    bin.find_sources_in_dirs('.')
    bin.includes = '../extra/b25/src ../lib'
    bin.target = 'tsniff'
    bin.uselib_local = 'capsts_staticlib'
    bin.uselib = 'GLIB'
